<?php


 /**
  * Session Value Object.
  * This class is value object representing database table teleprogramm_mir
  * This class is intented to be used together with associated Dao object.
  */

 /**
  * This sourcecode has been generated by FREE DaoGen generator version 2.4.1.
  * The usage of generated code is restricted to OpenSource software projects
  * only. DaoGen is available in http://titaniclinux.net/daogen/
  * It has been programmed by Tuomo Lukka, Tuomo.Lukka@iki.fi
  *
  * DaoGen license: The following DaoGen generated source code is licensed
  * under the terms of GNU GPL license. The full text for license is available
  * in GNU project's pages: http://www.gnu.org/copyleft/gpl.html
  *
  * If you wish to use the DaoGen generator to produce code for closed-source
  * commercial applications, you must pay the lisence fee. The price is
  * 5 USD or 5 Eur for each database table, you are generating code for.
  * (That includes unlimited amount of iterations with all supported languages
  * for each database table you are paying for.) Send mail to
  * "Tuomo.Lukka@iki.fi" for more information. Thank you!
  */




class Session {

    /** 
     * Persistent Instance variables. This data is directly 
     * mapped to the columns of database table.
     */
    var $sessionID;
    var $showID;
    var $sessionDateTime;
    var $title;



    /** 
     * Constructors. DaoGen generates two constructors by default.
     * The first one takes no arguments and provides the most simple
     * way to create object instance. The another one takes one
     * argument, which is the primary key of the corresponding table.
     */

    function Session () {

    }

    /* function Session ($sessionIDIn) {

          $this->sessionID = $sessionIDIn;

    } */


    /** 
     * Get- and Set-methods for persistent variables. The default
     * behaviour does not make any checks against malformed data,
     * so these might require some manual additions.
     */

    function getSessionID() {
          return $this->sessionID;
    }
    function setSessionID($sessionIDIn) {
          $this->sessionID = $sessionIDIn;
    }

    function getShowID() {
          return $this->showID;
    }
    function setShowID($showIDIn) {
          $this->showID = $showIDIn;
    }

    function getSessionDateTime() {
          return $this->sessionDateTime;
    }
    function setSessionDateTime($sessionDateTimeIn) {
          $this->sessionDateTime = $sessionDateTimeIn;
    }

    function getTitle() {
          return $this->title;
    }
    function setTitle($titleIn) {
          $this->title = $titleIn;
    }



    /** 
     * setAll allows to set all persistent variables in one method call.
     * This is useful, when all data is available and it is needed to 
     * set the initial state of this object. Note that this method will
     * directly modify instance variales, without going trough the 
     * individual set-methods.
     */

    function setAll($sessionIDIn,
          $showIDIn,
          $sessionDateTimeIn,
          $titleIn) {
          $this->sessionID = $sessionIDIn;
          $this->showID = $showIDIn;
          $this->sessionDateTime = $sessionDateTimeIn;
          $this->title = $titleIn;
    }


    /** 
     * hasEqualMapping-method will compare two Session instances
     * and return true if they contain same values in all persistent instance 
     * variables. If hasEqualMapping returns true, it does not mean the objects
     * are the same instance. However it does mean that in that moment, they 
     * are mapped to the same row in database.
     */
    function hasEqualMapping($valueObject) {

          if ($valueObject->getSessionID() != $this->sessionID) {
                    return(false);
          }
          if ($valueObject->getShowID() != $this->showID) {
                    return(false);
          }
          if ($valueObject->getSessionDateTime() != $this->sessionDateTime) {
                    return(false);
          }
          if ($valueObject->getTitle() != $this->title) {
                    return(false);
          }

          return true;
    }



    /**
     * toString will return String object representing the state of this 
     * valueObject. This is useful during application development, and 
     * possibly when application is writing object states in textlog.
     */
    function toString() {
        $out = $this->getDaogenVersion();
        $out = $out."\nclass Session, mapping to table teleprogramm_mir\n";
        $out = $out."Persistent attributes: \n"; 
        $out = $out."sessionID = ".$this->sessionID."\n"; 
        $out = $out."showID = ".$this->showID."\n"; 
        $out = $out."sessionDateTime = ".$this->sessionDateTime."\n"; 
        $out = $out."title = ".$this->title."\n"; 
        return $out;
    }


    /**
     * Clone will return identical deep copy of this valueObject.
     * Note, that this method is different than the clone() which
     * is defined in java.lang.Object. Here, the retuned cloned object
     * will also have all its attributes cloned.
     */
    function clone() {
        $cloned = new Session();

        $cloned->setSessionID($this->sessionID); 
        $cloned->setShowID($this->showID); 
        $cloned->setSessionDateTime($this->sessionDateTime); 
        $cloned->setTitle($this->title); 

        return $cloned;
    }



    /** 
     * getDaogenVersion will return information about
     * generator which created these sources.
     */
    function getDaogenVersion() {
        return "DaoGen version 2.4.1";
    }

}

?>